name: Test

on:
  push:
    branches: [main]
  pull_request:

env:
  WP_CLI_TEST_DBROOTUSER: root
  WP_CLI_TEST_DBROOTPASS: root
  WP_CLI_TEST_DBUSER: wp_cli_test
  WP_CLI_TEST_DBPASS: password1
  WP_CLI_TEST_DBNAME: wp_cli_test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
        wp: ['latest', '6.4']
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer install --no-interaction

      - run: composer prepare-tests
        env:
          WP_VERSION: ${{ matrix.wp }}
          WP_CLI_TEST_DBHOST: 127.0.0.1

      - run: composer test

      - run: composer behat
